[tool.poetry]
name = "folium-vectorgrid"
version = "0.1.0"
description = "VectorGrid plugin for folium"
authors = ["Benjamin Ramser <ahoi@ipwnd.pw>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
folium = "^0.14.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
gitlint = "^0.18.0"
pytest = "^7.2.0"
pre-commit = "^2.20.0"
black = "^22.10"
poethepoet = "^0.16.4"
isort = "^5.9.3"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
test       = "poetry run pytest -vv -s tests/"
test-cov   = "poetry run pytest -vv -s --cov=folium_vectorgrid tests/"
lint       = "flake8 ."
